env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest/style
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  # style
  prefer-arrow-callback: error
  import/order:
    - error
    - groups: [builtin, external, type, internal, [parent, sibling, index]]
      pathGroups: [{ pattern: '@medea/**', group: internal, position: before }]
      newlines-between: always
      pathGroupsExcludedImportTypes: [internal]
      alphabetize:
        order: 'asc'
        caseInsensitive: true
  # best practices
  '@typescript-eslint/explicit-module-boundary-types': error
