extends:
  - jimmy-guzman
  - jimmy-guzman/typescript
  - jimmy-guzman/jest
parserOptions:
  project: ['./tsconfig.json']
rules:
  # style
  import/order:
    - error
    - groups: [builtin, external, type, internal, [parent, sibling, index]]
      pathGroups: [{ pattern: '@medea/**', group: internal, position: before }]
      newlines-between: always
      pathGroupsExcludedImportTypes: [internal]
      alphabetize:
        order: 'asc'
        caseInsensitive: true
  import/no-extraneous-dependencies: off
