version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/.data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medea
